name: "cid"

services:
  app:
    build: .
    ports:
      - "8008:8008"
    environment:
      - FLASK_ENV=production
      - LOG_FILE=true
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs