name: Check Requirements Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  workflow_dispatch:

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install pip-tools
      run: pip install pip-tools
    
    - name: Check for outdated dependencies
      run: |
        pip-compile --upgrade requirements.txt
        git diff --exit-code requirements-diff.txt || {
          echo "::warning::Requirements file needs updates. Run 'pip-compile --upgrade requirements.txt' locally."
          exit 1
        }